
Vagrant.configure("2") do |config|
  
    # Every Vagrant development environment requires a box
    config.vm.box = "ubuntu/bionic64"
  
    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
     config.vm.network :public_network, ip: "192.168.1.120"
  
    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
     config.vm.synced_folder ".", "/vagrant"
  
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
     config.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end
    #
    # View the documentation for the provider you are using for more
    # information on available options.
  
    # Enable provisioning with a shell script.
    #config.vm.provision "shell", inline: <<-SHELL
    #  apt-get update
    #  apt-get install -y git build-essential byobu
    #SHELL
  end